{% set proj_name = salt['pillar.get']('proj_name','myproject') -%}
{% set mysql_user = proj_name|replace('-','')|truncate(15) %}
{% set mysql_db = mysql_user -%}
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: {{ mysql_db }}
  username: {{ mysql_user }}
  password: '{{ salt['grains.get']('' ~ mysql_db ~ ':' ~ mysql_user ~ '') }}'
